version: '3.7'

services:
  redis:
    container_name: redis
    platform: linux/x86_64
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./data/:/data
      - ./conf/redis.conf:/usr/local/conf/redis.conf
