# Configuration for kafka
application:
  github:
    pat: ${GG_PIGS_GTIHUB_PAT:THIS-IS-SECRET-VALUE}
    token: ${GG_PIGS_GTIHUB_TOKEN:THIS-IS-SECRET-VALUE}
    user: "95team"
    image:
      repo: "gg-pigs-image"
      repo-path: "images"
      raw-path: "https://raw.githubusercontent.com/95team/gg-pigs-image/main/"