# Configuration for kafka
application:
  kafka:
    consumer:
      enable: true
      default:
        bootstrap-server: ${GG_PIGS_KAFKA_BOOTSTRAP_SERVER:localhost:9092}
        group-id: "gg-pigs-api-consumer-group-default"
        auto-offset-reset: "earliest"
      ems:
        bootstrap-server: ${GG_PIGS_KAFKA_BOOTSTRAP_SERVER:localhost:9092}
        group-id: "gg-pigs-api-consumer-group-ems"
        auto-offset-reset: "earliest"
    producer:
      enable: true
      default:
        bootstrap-server: ${GG_PIGS_KAFKA_BOOTSTRAP_SERVER:localhost:9092}
        linger-ms: 10
      ems:
        bootstrap-server: ${GG_PIGS_KAFKA_BOOTSTRAP_SERVER:localhost:9092}
        topic-4-pr-noti-event: "gg-pigs-api-poster-request-noti-event"
        linger-ms: 10