# Configuration for project
spring:
  profiles:
    include:
      - redis
      - kafka
      - github
  datasource:
    url: ${GG_PIGS_DATASOURCE_URL:jdbc:mysql://localhost:3306/gg_pigs_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${GG_PIGS_DATASOURCE_USERNAME:root}
    password: ${GG_PIGS_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
  jpa:
    properties:
      format_sql: true
      default_batch_fetch_size: 100
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  # Configuration for SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: pigs95team@gmail.com
    password: ${GG_PIGS_SMTP_PASSWORD:THIS-IS-SECRET-VALUE}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: ${SERVER_PORT:8484}

# Configuration for application
application:
  admin:
    email: "pigs95team@gmail.com"
    emails:
      - "pigs95team@gmail.com"
      - "kihyun5741@gmail.com"
  mail:
    from: "pigs95team@gmail.com"
  cookie:
    login-cookie-name: "gg-login"
    login-cookie-domain: "localhost"
  jwt:
    security-key: ${GG_PIGS_JWT_SECRET_KEY:security-key(local)&security-key(local)&security-key(local)&security-key(local)}
    expiration-age: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
