# Configuration for project
spring:
  profiles:
    include:
      - redis
      - kafka
      - github
  datasource:
    url: jdbc:mysql://localhost:3306/gg_pigs_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2

  jpa:
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
        default_batch_fetch_size: 100
    database: h2
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

  # Configuration for SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: pigs95team@gmail.com
    password: "비밀 값입니다."
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Configuration for application
application:
  admin:
    email: "pigs95team@gmail.com"
    emails:
      - "pigs95team@gmail.com"
      - "kihyun5741@gmail.com"
  mail:
    from: "pigs95team@gmail.com"
  cookie:
    login-cookie-name: "gg-login"
    login-cookie-domain: "localhost"
  jwt:
    security-key: "security-key"
    expiration-age: 3600000